sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: thk01
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8ZxQumgnmbxgLGk4HM
    access-key-secret: yBXtNbdnn3jnZHnTEJ4EpNVr9bLweW
    bucket-name: 18435226130
  redis:
    host: thk01
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx239a986942906044
    secret: dbf2bfc90d8b7b2c44c658f23049c50d
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php